[package]
name = "pavis"
version = "0.0.1"
edition = "2021"

[dependencies]
pingora = { version = "0.6.0", features = ["proxy"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9.2"
http = "1.4.0"