[package]
name = "pavis-e2e"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true }
serde_yaml = "0.9"
pavis-core = { path = "../pavis-core" }
pavis-pvs = { path = "../pavis-pvs" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
