apiVersion: v1
kind: Service
metadata:
  name: pavis-relay
  namespace: bench-system
  labels:
    app: pavis-relay
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
  selector:
    app: pavis-relay
