[workspace]
members = [
    "crates/pavis",
    "crates/pavis-cli",
    "crates/pavis-xds",
    "crates/pavis-pvs",
    "crates/pavis-core",
    "crates/pavis-adapter-yaml",
    "crates/pavis-e2e",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
opt-level = 3
