[package]
name = "pavis-codec-serde"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Serde-based codecs for Pavis"

[dependencies]
# Pavis
pavis-core = { path = "../pavis-core", features = ["serde"] }
pavis-codec-api = { path = "../pavis-codec-api" }
pavis-ingest-api = { path = "../pavis-ingest-api" }

# Serialization / Input Formats
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
humantime-serde = "1.1.1"

# Validation & Error Handling
anyhow = { workspace = true }
thiserror = "1"
regex = "1"
http = "1.4.0"
# validator = { version = "0.16", features = ["derive"] } # Optional, can add later

[dev-dependencies]
bytes = "1"
