[package]
name = "pavis-relay"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Relay layer for Pavis"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
thiserror = "1"
axum = "0.7"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
futures-util = "0.3"
pavis-pvs = { path = "../pavis-pvs" }
pavis-ingest-api = { path = "../pavis-ingest-api" }
pavis-ingest-file = { path = "../pavis-ingest-file", optional = true }
pavis-codec-api = { path = "../pavis-codec-api" }
pavis-codec-serde = { path = "../pavis-codec-serde", optional = true }
pavis-core = { path = "../pavis-core" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }

[features]
default = ["ingest-file", "codec-serde"]
ingest-file = ["dep:pavis-ingest-file"]
codec-serde = ["dep:pavis-codec-serde"]
