[package]
name = "pavis-relay"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Relay layer for Pavis"

[dependencies]
thiserror = "1"
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
