#[path = "relay/r10_startup_corrupted_lkg.rs"]
pub mod r10_startup_corrupted_lkg;
#[path = "relay/r11_rapid_toggle.rs"]
pub mod r11_rapid_toggle;
#[path = "relay/r12_symlink_updates.rs"]
pub mod r12_symlink_updates;
#[path = "relay/r13_transient_permission_failure.rs"]
pub mod r13_transient_permission_failure;
#[path = "relay/r14_transient_empty_file.rs"]
pub mod r14_transient_empty_file;
#[path = "relay/r15_artifact_size_limits.rs"]
pub mod r15_artifact_size_limits;
#[path = "relay/r16_traceability.rs"]
pub mod r16_traceability;
#[path = "relay/r1_publish_success.rs"]
pub mod r1_publish_success;
#[path = "relay/r2_reject_invalid_pvs.rs"]
pub mod r2_reject_invalid_pvs;
#[path = "relay/r3_long_poll_semantics.rs"]
pub mod r3_long_poll_semantics;
#[path = "relay/r4_partial_write_protection.rs"]
pub mod r4_partial_write_protection;
#[path = "relay/r5_observability.rs"]
pub mod r5_observability;
#[path = "relay/r6_ingest_debouncing.rs"]
pub mod r6_ingest_debouncing;
#[path = "relay/r7_persistence_recovery.rs"]
pub mod r7_persistence_recovery;
#[path = "relay/r8_codec_validation.rs"]
pub mod r8_codec_validation;
#[path = "relay/r9_file_replacement.rs"]
pub mod r9_file_replacement;
