services:
  # The Sidecar Proxy
#  aegis:
#    build:
#      context: ..
#      dockerfile: crates/aegis/Dockerfile
#    ports:
#      - "8080:8080" # Proxy Port
#      - "9091:9091" # Metrics Port
#    volumes:
#      - ./aegis-config.yaml:/etc/aegis/config.yaml
#    environment:
#      - RUST_LOG=info
#    depends_on:
#      - backend-v1
#      - backend-v2

  # Upstream Service V1 (Echo Server)
  backend-v1:
    image: ealen/echo-server
    environment:
      - PORT=80
      - SERVICE_NAME=backend-v1
    ports:
      - "8081:80"

  # Upstream Service V2 (Echo Server)
  backend-v2:
    image: ealen/echo-server
    environment:
      - PORT=80
      - SERVICE_NAME=backend-v2
    ports:
      - "8082:80"