worker_processes 2;
worker_rlimit_nofile 20000;

error_log /dev/null;
pid /tmp/nginx.pid;

events {
    worker_connections 10000;
    use epoll;
    multi_accept on;
}

http {
    access_log off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    keepalive_requests 10000;

    upstream backend {
        server backend:80;
        keepalive 100;
    }

    server {
        listen 8082;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
        }
    }
}