[package]
name = "pavis-core"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Core primitives and engine for the Pavis data plane"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
rkyv = { version = "0.8", features = ["bytecheck"] }
bytecheck = "0.8"
rancor = "0.1"
serde = { workspace = true, optional = true }
regex = "1"
thiserror = "2"
http = "1.4"
compact_str = { version = "0.9", features = ["rkyv", "serde"] }

[dev-dependencies]
serde_json = "1.0"
