server:
  listen_addr: "0.0.0.0:8443"
  tls:
    enabled: true
    cert_path: "{}"
    key_path: "{}"
telemetry:
  level: "debug"
  access_log: "stdout"
upstreams:
  - name: "backend"
    endpoints:
      - ip: "127.0.0.1"
        port: {}
routes:
  - host: "*"
    paths:
      - path: "/"
        destinations:
          - upstream: "backend"
            weight: 1
