server:
  listen_addr: "${LISTEN_ADDR}"
telemetry:
  access_log: "stdout"
upstreams:
  - name: "backend-tls"
    tls:
      enabled: true
      verify_hostname: false
      verify_cert: false
    endpoints:
      - ip: "${UPSTREAM_HOST}"
        port: ${UPSTREAM_PORT}
routes:
  - host: "*"
    paths:
      - path: "/"
        destinations:
          - upstream: "backend-tls"
            weight: 1
