[package]
name = "pavis-pvs"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
description = "PVS file protocol boundary for Pavis"

[dependencies]
pavis-core = { path = "../pavis-core" }
rkyv = { version = "0.7", features = ["validation"] }
sha2 = "0.10.9"
thiserror = "1"
memmap2 = "0.9"

[dev-dependencies]
