name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Format & Lint
        run: |
          make fmt-check
          make lint
          make shellcheck

      - name: Run Unit Tests
        run: make test

      - name: Build Release Binary
        run: make binary-build CRATE=workspace

      - name: Log Binary Size
        run: |
          echo "Pavis Binary Size: $(du -h target/release/pavis | cut -f1)"
          echo "Pavctl Binary Size: $(du -h target/release/pavctl | cut -f1)"
          echo "Pavis-Relay Binary Size: $(du -h target/release/pavis-relay | cut -f1)"

      - name: Run E2E Tests for pavis in Binary
        run: make e2e-pavis-binary

      - name: Run E2E Tests for relay in Binary
        run: make e2e-relay-binary

      - name: Run E2E Tests for integrated in Binary
        run: make e2e-integrated-binary

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Pavis Docker Image
        run: make docker-build IMAGE=pavis MODE=ci

      - name: Build Relay Docker Image
        run: make docker-build IMAGE=relay MODE=ci

      - name: Build Mock Relay Relay Docker Image
        run: make docker-build IMAGE=mock-relay MODE=ci

      - name: Build Mock Upstream Docker Image
        run: make docker-build IMAGE=mock-upstream MODE=ci

      - name: Log Image Size
        run: |
          echo "Pavis Image Size: $(docker images --format '{{.Size}}' pavis:local)"
          echo "Relay Image Size: $(docker images --format '{{.Size}}' pavis-relay:local)"
          echo "Mock Relay Image Size: $(docker images --format '{{.Size}}' pavis-mock-relay:local)"
          echo "Mock Upstream Image Size: $(docker images --format '{{.Size}}' pavis-mock-upstream:local)"

      - name: Run E2E Tests for pavis in Docker
        run: make e2e-pavis-docker

      - name: Run E2E Tests for relay in Docker
        run: make e2e-relay-docker

      - name: Run E2E Tests for integrated in Docker
        run: make e2e-integrated-docker
